// Generates deterministic Ed25519 fixtures for quest_permit Move tests.
//
// Run once with `tsx scripts/gen_quest_permit_fixtures.ts` and paste the
// printed hex constants into tests/quest_permit_tests.move. The keypair is
// seeded from a fixed 32-byte buffer so re-running produces identical
// output — tests stay deterministic.
//
// Wire format MUST match quest_permit.move's peel order:
//   address recipient | u64 nonce | u8 kind | u8 tier_gate | u8 rarity
//   | vec<u8> name | vec<u8> walrus_id | vec<u8> equipped_value

import { Ed25519Keypair } from "@mysten/sui/keypairs/ed25519";
import { bcs } from "@mysten/sui/bcs";
import { normalizeSuiAddress } from "@mysten/sui/utils";

const SEED = new Uint8Array(32).fill(7); // arbitrary fixed seed
const kp = Ed25519Keypair.fromSecretKey(SEED);
const pubkey = kp.getPublicKey().toRawBytes(); // 32 bytes

const PermitBcs = bcs.struct("CosmeticMintPermit", {
  recipient: bcs.Address,
  nonce: bcs.u64(),
  kind: bcs.u8(),
  tier_gate: bcs.u8(),
  rarity: bcs.u8(),
  name: bcs.vector(bcs.u8()),
  walrus_identifier_standalone: bcs.vector(bcs.u8()),
  equipped_value: bcs.vector(bcs.u8()),
});

function strBytes(s: string): number[] {
  return Array.from(new TextEncoder().encode(s));
}

async function fixture(label: string, p: {
  recipient: string;
  nonce: bigint;
  kind: number;
  tier_gate: number;
  rarity: number;
  name: string;
  walrus: string;
  equipped: string;
}) {
  const payload = PermitBcs.serialize({
    recipient: p.recipient,
    nonce: p.nonce,
    kind: p.kind,
    tier_gate: p.tier_gate,
    rarity: p.rarity,
    name: strBytes(p.name),
    walrus_identifier_standalone: strBytes(p.walrus),
    equipped_value: strBytes(p.equipped),
  }).toBytes();

  // Plain Ed25519 signature over raw payload bytes (no intent prefix).
  const { signature: sigWithFlag } = await kp.signPersonalMessage(payload);
  // signPersonalMessage prepends intent + applies Blake2b hashing — we
  // can't use it. Use raw signing directly via the keypair's internal API.
  // Ed25519Keypair exposes `sign` which signs raw bytes.
  // (Older versions: `signData`; current SDK exposes `sign`.)
  void sigWithFlag;
  const rawSig = await (kp as unknown as { sign: (m: Uint8Array) => Promise<Uint8Array> }).sign(payload);

  console.log(`\n// ── ${label} ─────────────────────────────────────────`);
  console.log(`// recipient = ${p.recipient}`);
  console.log(`// nonce = ${p.nonce}`);
  console.log(`// kind=${p.kind} tier_gate=${p.tier_gate} rarity=${p.rarity}`);
  console.log(`// name=${JSON.stringify(p.name)} walrus=${JSON.stringify(p.walrus)} equipped=${JSON.stringify(p.equipped)}`);
  console.log(`const PAYLOAD_${label}: vector<u8> = x"${Buffer.from(payload).toString("hex")}";`);
  console.log(`const SIG_${label}: vector<u8> = x"${Buffer.from(rawSig).toString("hex")}";`);
}

async function main() {
  console.log(`// Generated by scripts/gen_quest_permit_fixtures.ts — do not edit manually.`);
  console.log(`const PUBKEY: vector<u8> = x"${Buffer.from(pubkey).toString("hex")}";`);

  // Recipient address for tests — matches ALICE = @0xA11CE in the Move
  // tests. BCS Address serializer accepts the 0x-prefixed canonical form.
  const ALICE = normalizeSuiAddress("0xa11ce");
  const BOB = normalizeSuiAddress("0xb0b");

  await fixture("VALID_OUTFIT", {
    recipient: ALICE,
    nonce: 42n,
    kind: 0, // outfit
    tier_gate: 5,
    rarity: 2, // epic
    name: "Tuxedo",
    walrus: "tuxedo-standalone-id",
    equipped: "Tuxedo",
  });

  await fixture("VALID_BG", {
    recipient: ALICE,
    nonce: 43n,
    kind: 1, // background
    tier_gate: 3,
    rarity: 1, // rare
    name: "Ballroom",
    walrus: "ballroom-standalone-id",
    equipped: "Ballroom",
  });

  await fixture("BOB_RECIPIENT", {
    recipient: BOB,
    nonce: 99n,
    kind: 0,
    tier_gate: 1,
    rarity: 0,
    name: "Plain Tee",
    walrus: "plain-tee-id",
    equipped: "PlainTee",
  });
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
